version: "3.8"

services:
  web:
    build: .
    ports:
      - "3100:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: ruby:3.1.2
    command: tail -f /dev/null
    volumes:
      - .:/app
