version: "3.8"

services:
  web:
    build: .
    ports:
      - "3100:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - BETTING_CLOSED=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MySuperPassword
  db:
    container_name: postgres-wc
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MySuperPassword
    ports:
      - "5433:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data